### ISSUE TITLE
许多训练的问题

### ISSUE THREAD

**Issue by NoctisJOJO** [Traffic-X/MonoUNI#24]
作者您好，感谢你开源的代码，我是武汉大学的学生，第一次接触深度学习，在训练你的代码时，遇到许多问题，想请教一下。
# 1.训练时内存不足
我使用AutoDL平台，使用一张2080Ti进行训练，显存11G，内存40G，batchsize=8。每次在训练到第三个epoch时，就会由于内存超出而停止，原因是每个epoch保存了全部数据？
这是一张2080Ti，40G内存
![image](https://github.com/user-attachments/assets/04ff0c50-c041-41b9-9469-8b9fffb76f8c)
随后我尝试两张2080Ti，80G内存，结果为第四个epoch内存超出
![image](https://github.com/user-attachments/assets/cc0bcc6d-dfb9-435f-b8ca-e5871a6edfb2)
这是内存超出时的状态
![image](https://github.com/user-attachments/assets/4fcc3b2d-c689-4a53-a114-a848df1faf24)
我通过询问chatgpt，在每个epoch后加上 torch.cuda.empty_cache()，仍然无法解决问题，解决方法只有加大内存吗？作者在训练时，也是内存随着每个epoch逐步增加的吗，因为我对MonoUNI代码阅读并不完全，不知道是否有内存释放的代码。

# 2.多卡训练问题
同样是AutoDL平台，我使用4张2080TI，试图进行多卡训练，但是，偶尔会总是有gpu不工作（下面会解释）
在我使用4张卡时，gpu[0]和gpu[2]正常工作，gpu[1]和gpu[3]则是在报错后停止工作
报错为‘THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=700 : an illegal memory access was encountered‘
下图为gpu工作的监控
![image](https://github.com/user-attachments/assets/9aae5880-b5eb-466b-9d51-201b5dc99125)
随后我尝试两张卡，gpu[0]工作，gpu[1]不工作；三张卡，gpu[0]和gpu[2]工作，gpu[1]不工作。
这或许是我服务器的问题，因为我只用一张卡的时候，有时也会报同样的错误，换一张卡后该错误就不在了。
我想请问作者是否遇到过该问题

# 3. 地平面方程问题
Rope3d数据集中给出了地平面方程，但是dair-v2x路端数据集中并没有给出地平面方程，请问作者是如何解决这问题的。
我通过标签信息，使用车辆与地面的接触点，拟合地平面方程，可结果不尽人意
这是rope3d数据集中的地平面方程参数：0.008187128 -0.975265 -0.2208872 7.23388195038，并且同一个场景下的参数都相同
这是我自己生成的地平面方程参数：0.0026061970708190657 -0.9749178010425128 -0.22255004734901618 7.274439125314834
0.007552327858852356 -0.9749791380058083 -0.22216805135756798 7.290804489336864
......
每张不同的图片生成的地平面都不同，我想请问作者是如何解决在dair-v2x路端数据集训练时地平面方程的问题的

# 4. 深度立方体问题
![image](https://github.com/user-attachments/assets/55a54074-f746-4b89-95ec-08148204edb2)
我尝试根据论文生成这些立方体，但由于我的代码基础较差，遇到了不少困难。
请问作者能否给出这部分代码，不方便的话我就再努力尝试下orz

**Comment by NoctisJOJO** [comment]
更新下
1、2、4已解决
3 地平面方程问题仍未解决。

**Comment by NoctisJOJO** [comment]
更新下
1、2、4已解决
3 地平面方程问题仍未解决。

**Comment by yfCheng-CUMTB** [comment]
你好，请问解决monouni使用dairv2x数据集训练的问题了吗

**Comment by JiashuoTian** [comment]
您好，请问您是如何解决训练时内存不足的问题的？如果是增加训练内存的话，设置为多少比较合适呢

**Comment by yfCheng-CUMTB** [comment]
您好！我后来发现monouni的数据集不支持我想用的dair数据集就没有再跑了。祝工作顺利！发自我的手机-------- 原始邮件 --------发件人： JiashuoTian ***@***.***>日期： 2025年3月5日周三 07:37收件人： Traffic-X/MonoUNI ***@***.***>抄送： cyf-cumtb ***@***.***>, Comment ***@***.***>主    题： Re: [Traffic-X/MonoUNI] 许多训练的问题 (Issue #24)
  您好，请问您是如何解决训练时内存不足的问题的？如果是增加训练内存的话，设置为多少比较合适呢—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



JiashuoTian left a comment (Traffic-X/MonoUNI#24)
您好，请问您是如何解决训练时内存不足的问题的？如果是增加训练内存的话，设置为多少比较合适呢

**Comment by mingjunjun** [comment]
请问可以网盘分享一下你下载的DAIR-V2X-I 数据集吗？原来的官方网址打不开了

**Comment by yfCheng-CUMTB** [comment]
可官方GitHub补了谷歌网盘的链接，可以看一下发自我的手机-------- 原始邮件 --------发件人： 稀罕 ***@***.***>日期： 2025年3月25日周二 21:21收件人： Traffic-X/MonoUNI ***@***.***>抄送： cyf-cumtb ***@***.***>, Comment ***@***.***>主    题： Re: [Traffic-X/MonoUNI] 许多训练的问题 (Issue #24)
  请问可以网盘分享一下你下载的DAIR-V2X-I 数据集吗？原来的官方网址打不开了—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



mingjunjun left a comment (Traffic-X/MonoUNI#24)
请问可以网盘分享一下你下载的DAIR-V2X-I 数据集吗？原来的官方网址打不开了

**Comment by mingjunjun** [comment]
好的谢谢，看到啦！

**Comment by Reborn888** [comment]
您好，我想请问一下您是如何生成图像的深度图的？ @NoctisJOJO

**Comment by NoctisJOJO** [comment]
> 您好，我想请问一下您是如何生成图像的深度图的？ [@NoctisJOJO](https://github.com/NoctisJOJO)

按论文里的描述生成就行，代码并不复杂，我放在我的仓库里了

**Comment by Reborn888** [comment]
谢谢谢谢！！ 是按照MonoUNI论文吗，但我没看到具体的生成方法啊。我现在想训练自己的数据集，但我的数据集里没有深度图这一部分，我想知道如何得到呢？有机会的话可以加下您的qq聊一下吗？我的qq：1042976225 @NoctisJOJO

**Comment by Reborn888** [comment]
> > 您好，我想请问一下您是如何生成图像的深度图的？ [@NoctisJOJO](https://github.com/NoctisJOJO)
> 
> 按论文里的描述生成就行，代码并不复杂，我放在我的仓库里了

感谢感谢！！！
